# This is an example of what an '_config.yml' file should look like
# when using jekyll-shell-theme. You should use this as a guide or
# just copy+paste it and modify some of the content to begin with.

title: Portal
email: mark@nitwit.se
description: >- # this means to ignore newlines until "baseurl:"
  Firefox Portal Page.
baseurl: "/portal" # the subpath of your site
url: "nitwit.se" # the base hostname & protocol for your site
hide_footer: true
hide_header: true

# Required plugins for the theme to work properly
plugins:
  - jekyll-remote-theme
  - jemoji

# Including jekyll-shell-theme using the jekyll-remote-theme plugin
remote_theme: nitwit-se/jekyll-chinolor-shell-theme

sass:
  style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - index.md

# controls how big the shell and font looks
font-size: large # options: [small] or [large]
